#!/bin/bash
PC=/home/<user>/sar16_work/proj_paper_core
echo "=== /tmp total ==="
du -sh /tmp 2>/dev/null
echo
echo "=== /tmp top-level entries by size (top 25) ==="
du -sh /tmp/* 2>/dev/null | sort -rh | head -25
echo
echo "=== are the /tmp run_*.sh regenerated by reproduce_all.sh? ==="
grep -n 'tmp' $PC/scripts/reproduce_all.sh | head -12
echo
echo "=== count /tmp entries ==="
ls -1 /tmp | wc -l
